spring:
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/face_recognition?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  redis:
    host: localhost
    jedis:
      pool:
        max-wait: 30
        enabled: true
        min-idle: 1
        max-idle: 5
        max-active: 8

face:
  config:
    # 构建FaceTeplate开关
    enable: true
    apiSecret: 1ZV70Hh5JbP1KEKL0m-INs_zRJbNfKHo
    apiKey: -YYaph4xNJN-ZSr3bDDnRxm8QazoCkPe
    # 第三方接口服务地址
    baseUrl: https://api-cn.faceplusplus.com/facepp/v3
    # 人脸相似度通过标准
    confidence: 85

# 临时文件存放目录（windows）
tempFile: D:/tempFile/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
tencent:
  sms:
    enable: true
    signName: 想吃肉0公众号
    templateId: 1713523
    secretId: AKID2a2OYUFPPEpEvTntrmbHpJafYHqJE152
    secretKey: zmNo23reJpBVhnsqgPwHS7f7QdgYEfx6
    SdkAppId: 1400798338

baidu:
  config:
    enable: true
    ak: QcKshLHzPB9mMAVq1yFvsAk6oldKcpXu