server:
  port: 8081
  servlet:
    context-path: /FaceRecognition


face:
  config:
    enable: true
    apiSecret: 1ZV70Hh5JbP1KEKL0m-INs_zRJbNfKHo
    apiKey: -YYaph4xNJN-ZSr3bDDnRxm8QazoCkPe
    baseUrl: https://api-cn.faceplusplus.com/facepp/v3
    # 人脸相似度通过标准
    confidence: 85